const actionPrefix = 'appAction';

const actionTypes = {
	ERROR_SET: `${actionPrefix}/ERROR_SET`,
	ERROR_CLEAR: `${actionPrefix}/ERROR_CLEAR`,

	SET_PLAYER_IN_LOCATION: `${actionPrefix}/SET_PLAYER_IN_LOCATION`,
	SET_PLAYER_INVENTORY: `${actionPrefix}/SET_PLAYER_INVENTORY`,
	ADD_ITEM_TO_PLAYER_INVENTORY: `${actionPrefix}/ADD_ITEM_TO_PLAYER_INVENTORY`,
	REMOVE_ITEM_FROM_PLAYER_INVENTORY: `${actionPrefix}/REMOVE_ITEM_FROM_PLAYER_INVENTORY`,

	MAP_CHANGE_POSITION: `${actionPrefix}/MAP_CHANGE_POSITION`,
	MAP_START_DRAG: `${actionPrefix}/MAP_START_DRAG`,
	MAP_STOP_DRAG: `${actionPrefix}/MAP_STOP_DRAG`,
	MAP_ADD_ELEMENT: `${actionPrefix}/MAP_ADD_ELEMENT`,
	MAP_CHANGE_DESTINATION: `${actionPrefix}/MAP_CHANGE_DESTINATION`,
	MAP_CHANGE_PLAYER_POSITION: `${actionPrefix}/MAP_CHANGE_PLAYER_POSITION`,

	LOCATION_SET_TYPE: `${actionPrefix}/LOCATION_SET_TYPE`,
	LOCATION_SET_INITIAL_DATA: `${actionPrefix}/LOCATION_SET_INITIAL_DATA`,
	LOCATION_SET_MAP: `${actionPrefix}/LOCATION_SET_MAP`,
	LOCATION_SET_PLAYER_POSITION: `${actionPrefix}/LOCATION_SET_PLAYER_POSITION`,
};

export default actionTypes;
